/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7705b6a5-762d-4fe3-9bf6-49ef19ff2b50",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ZkWMsZMMc",
    "aws_user_pools_web_client_id": "ma7pd10go13p9g4cdq584l5pb",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "FAMILY_NAME",
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "stripetable-dev",
            "region": "us-east-2"
        },
        {
            "tableName": "CUSTOMERS-dev",
            "region": "us-east-2"
        }
    ],
    "aws_user_files_s3_bucket": "cloneai-media-bucket184448-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_cloud_logic_custom": [
        {
            "name": "stripeapi",
            "endpoint": "https://6go7dv0wak.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "customers",
            "endpoint": "https://zm9asu0qrc.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "cloneaiCustomersApi",
            "endpoint": "https://3xwelgo4qg.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
